// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 22:53:16 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../sundials-master/include/sundials/sundials_types.h"
#include "../sundials-master/include/sundials/sundials_math.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

