// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 22:53:16 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Sundial's nvector-serial
*/
package test
