// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 22:53:16 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package test

/*
#cgo LDFLAGS: -L/usr/lib -Wl,--no-warn-mismatch
#include "../sundials-master/include/sundials/sundials_types.h"
#include "../sundials-master/include/sundials/sundials_math.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// SUNRpowerI function as declared in sundials/sundials_math.h:146
func SUNRpowerI(base Realtype, exponent int32) Realtype {
	cbase, _ := (C.realtype)(base), cgoAllocsUnknown
	cexponent, _ := (C.int)(exponent), cgoAllocsUnknown
	__ret := C.SUNRpowerI(cbase, cexponent)
	__v := (Realtype)(__ret)
	return __v
}

// SUNRpowerR function as declared in sundials/sundials_math.h:161
func SUNRpowerR(base Realtype, exponent Realtype) Realtype {
	cbase, _ := (C.realtype)(base), cgoAllocsUnknown
	cexponent, _ := (C.realtype)(exponent), cgoAllocsUnknown
	__ret := C.SUNRpowerR(cbase, cexponent)
	__v := (Realtype)(__ret)
	return __v
}
