// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 22:53:16 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package test

/*
#cgo LDFLAGS: -L/usr/lib -Wl,--no-warn-mismatch
#include "../sundials-master/include/sundials/sundials_types.h"
#include "../sundials-master/include/sundials/sundials_math.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Realtype type as declared in sundials/sundials_types.h:81
type Realtype float64

// Sunindextype type as declared in sundials/sundials_types.h:109
type Sunindextype int
