// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Apr 2019 00:38:31 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <stdio.h>
#include <sundials/sundials_types.h>
#include <sundials/sundials_nvector.h>
#include <sundials/sundials_fnvector.h>
#include <nvector/nvector_serial.h>
#include <sundials/sundials_math.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

