// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Apr 2019 00:38:31 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nvector

/*
#cgo LDFLAGS: -lsundials_nvecserial -L/usr/lib
#include <stdio.h>
#include <sundials/sundials_types.h>
#include <sundials/sundials_nvector.h>
#include <sundials/sundials_fnvector.h>
#include <nvector/nvector_serial.h>
#include <sundials/sundials_math.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// BIGREAL as defined in sundials/sundials_types.h:83
	BIGREAL = 0
	// SMALLREAL as defined in sundials/sundials_types.h:84
	SMALLREAL = 0
	// UNITROUNDOFF as defined in sundials/sundials_types.h:85
	UNITROUNDOFF = 0
	// SUNFALSE as defined in sundials/sundials_types.h:133
	SUNFALSE = 0
	// SUNTRUE as defined in sundials/sundials_types.h:137
	SUNTRUE = 1
	// SUNDIALSVERSION as defined in sundials/sundials_config.h:22
	SUNDIALSVERSION = "4.1.0"
	// SUNDIALSVERSIONMAJOR as defined in sundials/sundials_config.h:23
	SUNDIALSVERSIONMAJOR = 4
	// SUNDIALSVERSIONMINOR as defined in sundials/sundials_config.h:24
	SUNDIALSVERSIONMINOR = 1
	// SUNDIALSVERSIONPATCH as defined in sundials/sundials_config.h:25
	SUNDIALSVERSIONPATCH = 0
	// SUNDIALSVERSIONLABEL as defined in sundials/sundials_config.h:26
	SUNDIALSVERSIONLABEL = ""
	// SUNDIALSDOUBLEPRECISION as defined in sundials/sundials_config.h:52
	SUNDIALSDOUBLEPRECISION = 1
	// SUNDIALSINT64T as defined in sundials/sundials_config.h:60
	SUNDIALSINT64T = 1
	// SUNDIALSINDEXTYPE as defined in sundials/sundials_config.h:65
	SUNDIALSINDEXTYPE = 0
	// SUNDIALSMPIENABLED as defined in sundials/sundials_config.h:101
	SUNDIALSMPIENABLED = 1
)

// NVectorID as declared in sundials/sundials_nvector.h:71
type NVectorID int32

// NVectorID enumeration from sundials/sundials_nvector.h:71
const (
	SUNDIALSNVECSERIAL    NVectorID = iota
	SUNDIALSNVECPARALLEL  NVectorID = 1
	SUNDIALSNVECOPENMP    NVectorID = 2
	SUNDIALSNVECPTHREADS  NVectorID = 3
	SUNDIALSNVECPARHYP    NVectorID = 4
	SUNDIALSNVECPETSC     NVectorID = 5
	SUNDIALSNVECCUDA      NVectorID = 6
	SUNDIALSNVECRAJA      NVectorID = 7
	SUNDIALSNVECOPENMPDEV NVectorID = 8
	SUNDIALSNVECTRILINOS  NVectorID = 9
	SUNDIALSNVECCUSTOM    NVectorID = 10
)

const ()
