// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Apr 2019 00:38:31 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Sundial's nvector-serial
*/
package nvector
