// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Apr 2019 00:38:31 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nvector

/*
#cgo LDFLAGS: -lsundials_nvecserial -L/usr/lib
#include <stdio.h>
#include <sundials/sundials_types.h>
#include <sundials/sundials_nvector.h>
#include <sundials/sundials_fnvector.h>
#include <nvector/nvector_serial.h>
#include <sundials/sundials_math.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Realtype type as declared in sundials/sundials_types.h:81
type Realtype float64

// Sunindextype type as declared in sundials/sundials_types.h:109
type Sunindextype int

// NVectorContentSerial as declared in nvector/nvector_serial.h:60
type NVectorContentSerial struct {
	Length         Sunindextype
	OwnData        int32
	Data           []Realtype
	ref469bbb76    *C.N_VectorContent_Serial
	allocs469bbb76 interface{}
}

// FILE as declared in types/FILE.h:7
type FILE struct {
	Flags          int32
	IOReadPtr      []byte
	IOReadEnd      []byte
	IOReadBase     []byte
	IOWriteBase    []byte
	IOWritePtr     []byte
	IOWriteEnd     []byte
	IOBufBase      []byte
	IOBufEnd       []byte
	IOSaveBase     []byte
	IOBackupBase   []byte
	IOSaveEnd      []byte
	Fileno         int32
	Flags2         int32
	OldOffset      int
	CurColumn      uint16
	VtableOffset   byte
	Shortbuf       [1]byte
	Lock           unsafe.Pointer
	Offset         int
	FreeresBuf     unsafe.Pointer
	_Pad5          uint
	Mode           int32
	Unused2        [20]byte
	refba0adba4    *C.FILE
	allocsba0adba4 interface{}
}

// NVectorOps as declared in sundials/sundials_nvector.h:79
type NVectorOps struct {
	Nvgetvectorid                  NVectorID
	Nvclone                        NVector
	Nvcloneempty                   NVector
	Nvdestroy                      *func(arg0 NVector)
	Nvspace                        *func(arg0 NVector, arg1 []Sunindextype, arg2 []Sunindextype)
	Nvgetarraypointer              Realtype
	Nvsetarraypointer              *func(arg0 []Realtype, arg1 NVector)
	Nvlinearsum                    *func(arg0 Realtype, arg1 NVector, arg2 Realtype, arg3 NVector, arg4 NVector)
	Nvconst                        *func(arg0 Realtype, arg1 NVector)
	Nvprod                         *func(arg0 NVector, arg1 NVector, arg2 NVector)
	Nvdiv                          *func(arg0 NVector, arg1 NVector, arg2 NVector)
	Nvscale                        *func(arg0 Realtype, arg1 NVector, arg2 NVector)
	Nvabs                          *func(arg0 NVector, arg1 NVector)
	Nvinv                          *func(arg0 NVector, arg1 NVector)
	Nvaddconst                     *func(arg0 NVector, arg1 Realtype, arg2 NVector)
	Nvdotprod                      Realtype
	Nvmaxnorm                      Realtype
	Nvwrmsnorm                     Realtype
	Nvwrmsnormmask                 Realtype
	Nvmin                          Realtype
	Nvwl2norm                      Realtype
	Nvl1norm                       Realtype
	Nvcompare                      *func(arg0 Realtype, arg1 NVector, arg2 NVector)
	Nvinvtest                      *func(arg0 NVector, arg1 NVector) int32
	Nvconstrmask                   *func(arg0 NVector, arg1 NVector, arg2 NVector) int32
	Nvminquotient                  Realtype
	Nvlinearcombination            *func(arg0 int32, arg1 []Realtype, arg2 []NVector, arg3 NVector) int32
	Nvscaleaddmulti                *func(arg0 int32, arg1 []Realtype, arg2 NVector, arg3 []NVector, arg4 []NVector) int32
	Nvdotprodmulti                 *func(arg0 int32, arg1 NVector, arg2 []NVector, arg3 []Realtype) int32
	Nvlinearsumvectorarray         *func(arg0 int32, arg1 Realtype, arg2 []NVector, arg3 Realtype, arg4 []NVector, arg5 []NVector) int32
	Nvscalevectorarray             *func(arg0 int32, arg1 []Realtype, arg2 []NVector, arg3 []NVector) int32
	Nvconstvectorarray             *func(arg0 int32, arg1 Realtype, arg2 []NVector) int32
	Nvwrmsnormvectorarray          *func(arg0 int32, arg1 []NVector, arg2 []NVector, arg3 []Realtype) int32
	Nvwrmsnormmaskvectorarray      *func(arg0 int32, arg1 []NVector, arg2 []NVector, arg3 NVector, arg4 []Realtype) int32
	Nvscaleaddmultivectorarray     *func(arg0 int32, arg1 int32, arg2 []Realtype, arg3 []NVector, arg4 [][]NVector, arg5 [][]NVector) int32
	Nvlinearcombinationvectorarray *func(arg0 int32, arg1 int32, arg2 []Realtype, arg3 [][]NVector, arg4 []NVector) int32
	ref25b9efb8                    *C.N_Vector_Ops
	allocs25b9efb8                 interface{}
}

// NVector as declared in sundials/sundials_nvector.h:82
type NVector struct {
	Content        unsafe.Pointer
	Ops            GenericNVectorOps
	refdb950bdc    *C.N_Vector
	allocsdb950bdc interface{}
}

// NVectorS as declared in sundials/sundials_nvector.h:85
type NVectorS struct {
	Content        unsafe.Pointer
	Ops            GenericNVectorOps
	ref86072daf    **C.N_Vector
	allocs86072daf interface{}
}
